### ISSUE TITLE
DomainAge /WhoIS proxy problems

### ISSUE THREAD

**Issue by GeorgiNikolovRMA** [RUCD/mark#29]
Need to find a way for WhoIS to connect via a PROXY or use WhoIS web service, DomainAge takes too long if Proxy not configured and with proxy gives error:

    at java.net.HttpConnectSocketImpl.doTunneling(HttpConnectSocketImpl.java:181)
    at java.net.HttpConnectSocketImpl.doTunnel(HttpConnectSocketImpl.java:168)
    at java.net.HttpConnectSocketImpl.access$200(HttpConnectSocketImpl.java:44)
    at java.net.HttpConnectSocketImpl$2.run(HttpConnectSocketImpl.java:151)
    at java.net.HttpConnectSocketImpl$2.run(HttpConnectSocketImpl.java:149)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.HttpConnectSocketImpl.privilegedDoTunnel(HttpConnectSocketImpl.java:148)
    at java.net.HttpConnectSocketImpl.connect(HttpConnectSocketImpl.java:111)
    at java.net.Socket.connect(Socket.java:589)
    at org.apache.commons.net.SocketClient.connect(SocketClient.java:182)
    at org.apache.commons.net.SocketClient.connect(SocketClient.java:203)
    at org.apache.commons.net.SocketClient.connect(SocketClient.java:296)
    at netrank.DomainAge.initWhois(DomainAge.java:71)
    at netrank.DomainAge.analyze(DomainAge.java:145)
    at netrank.DomainAgeTest.testAnalyze(DomainAgeTest.java:41)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at java.net.HttpConnectSocketImpl.doTunneling(HttpConnectSocketImpl.java:179)
    ... 36 more
Caused by: java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 503 Service Unavailable"
    at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2124)
    ... 41 more

http://www.webservicex.net/whois.asmx?op=GetWhoIS

http://www.webservicex.net/whois.asmx/GetWhoIS?HostName=rma.ac.be

**Comment by tdebatty** [comment]
direct whois queries might be blocked on some networks => create another agent that uses a web service instead

ex:
http://www.webservicex.net/whois.asmx?op=GetWhoIS
view-source:http://www.webservicex.net/whois.asmx/GetWhoIS?HostName=rma.ac.be
